name = "cf-worker-ws-dev"
main = "src/index.js"
compatibility_date = "2024-01-01"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "793785b0-ae92-46ae-b5dc-e4a430af5123"
# TROJAN_PASSWORD = "lizzy-02"  # Optional: If not set, UUID will be used as password
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
